Create unit party
kujiraOo/penlearn pull request #26
Opened 2021-04-17 18:25 UTC by PenguinSatan

2021-04-17 22:03 UTC, kujiraOo requested changes

2021-04-17 22:03 UTC, kujiraOo commented on battle/round-system.js
> +  (movePoints1, movePoints2) => movePoints2.movePoints - movePoints1.movePoints,
rename `movePoints1, movePoints2` to either `unit1, unit2` or just `a, b`

2021-04-17 22:03 UTC, kujiraOo commented on battle/round-system.js
> +  const newUnitsArray = units.map(copyUnit);
i would prefer `newUnitsArray` -> `newUnitArray`

2021-04-17 22:03 UTC, kujiraOo commented on battle/round-system.js
> +const copyUnit = (unit) => ({ ...unit });
maybe rename it to `copyObject`, as it actually works with any object, not only `unit`

2021-04-17 22:48 UTC, kujiraOo commented
closes #22

2021-04-17 22:50 UTC, kujiraOo commented
please rename the PR title to smth like "Add logic for calculating turn queue"

2021-04-18 18:00 UTC, PenguinSatan commented on battle/create-unit.js
> +  const aglRng = random.randomAgl();
done

2021-04-18 18:02 UTC, PenguinSatan commented on battle/round-system.js
> +// console.log(restoreMovepoints(turnLog));
fixed, unused things moved to coments for future use

2021-04-18 18:03 UTC, PenguinSatan commented on battle/round-system.js
> +console.log(turnQueue(turnLog).map(unitToTurnLogItem));
126 deleted

2021-04-18 18:07 UTC, PenguinSatan commented on battle/round-system.js
> +// console.log(restoreMovepoints(turnLog));
done

2021-04-18 18:20 UTC, PenguinSatan commented on battle/round-system.js
> +  const newUnitsArray = units.map(copyUnit);
as u wish

2021-04-18 18:20 UTC, PenguinSatan commented on battle/round-system.js
> +const copyUnit = (unit) => ({ ...unit });
agree

2021-04-18 20:37 UTC, kujiraOo approved these changes

2021-04-18 20:37 UTC, merged